### ISSUE TITLE
CLI options

### ISSUE THREAD

**Issue by firecat53** [l4l/yofi#113]
Hey, sorry to spam you with all these issues recently!

I noticed that the CLI arguments are ordered as `yofi [FLAGS] [OPTIONS] [SUBCOMMANDS]`. It seems like a more common pattern for CLI options is `yofi [OPTIONS] [SUBCOMMAND] [FLAGS]`. 

- `[OPTIONS]` are global to everything (e.g. `--help` and `--config-file`).
- `[FLAGS]` are applicable only to a subcommand (e.g. `yofi dialog -p 'Enter name'`).

I'd suggest that the global `yofi -h` only show the global `[OPTIONS]`, and `yofi dialog -h` would show the applicable flags `--prompt` and `--password` since those two flags are not used with `apps` and `binapps`.

Also, right now it seems awkward that `yofi dialog -p 'Enter name'` doesn't work but `yofi -p 'Enter name' dialog` does.

Thanks!

**Comment by l4l** [comment]
> I noticed that the CLI arguments are ordered as `yofi [FLAGS] [OPTIONS] [SUBCOMMANDS]`.

It's not particularly the full form of it. I would rather describe it as `yofi [FLAGS] [OPTIONS] [SUBCOMMAND]  [SUBCOMMAND-FLAGS] [SUBCOMMAND-OPTIONS]`. You may look into the subcomand flags via the same `-h` flag after the subcommand itself, e.g `yofi apps -h`. But there's not many of these anyway.

So essentially both `[FLAGS]` and `[OPTIONS]` a global and can be used with any subcommand, e.g: `yofi -p 'prompt' binapps` & `yofi -p 'prompt' apps` & `echo -e '1\n2\n3' | yofi -p 'prompt' dialog`. That's why it's not possible to use it this way: `yofi apps -p 'prompt'`.

Hope that explanation helps. Unfortunately there's no much user-docs for [`structopt`](https://docs.rs/structopt/latest/structopt/) that generates all of this docs and ensures the flags order.

**Comment by firecat53** [comment]
Ok, it's not a huge deal :smiley: Thanks for the response!
