### ISSUE TITLE
Publish on crates.io

### ISSUE THREAD

**Issue by arlyon** [l4l/yofi#73]
Great project!

I'd like to be able to install it will cargo:

```
cargo install yofi
```

This means I can also update via cargo as well, rather than have to find the binary. Is that something you'd be willing to add to CI?

**Comment by l4l** [comment]
To be honest I would love to. But the problem is that some of the dependencies has my own patches (raqote, freedesktop_entry_parser, fzyr, systemd-journal-logger) and crates.io doesn't really allow that. It seems only raqote patch (https://github.com/jrmuizel/raqote/pull/171) is critical so I might think of some workaround/removal these features.

**Comment by l4l** [comment]
Published :tada: https://crates.io/crates/yofi

Linked PR: #127
